### PR TITLE
Add notes and example for Analytics API 1.4

### PR DESCRIPTION
**Pull request by duynguyen**

### CODE REVIEW

**Review by meryllblanchet — CHANGES_REQUESTED** [review]
Thanks for the contribution @duynguyen !

What about recommending the usage of the `Generic` action template that comes with the appropriate wiring to our SDK and demonstrates how to consume a generic API endpoint from a Runtime action?

**Comment by sarahxxu** [comment]
@meryllblanchet are you referring to the code example attached? which part of our SDK do you have in mind to add (note this is 1.4)?

**Comment by meryllblanchet** [comment]
@sarahxxu Looking at @duynguyen 's code it seems to me that he did it very well and used the CLI to bootstrap a Runtime action based on the `Generic` [template](https://github.com/adobe/generator-aio-app/blob/master/generators/add-action/generic/index.js).

My point is that the documentation snippet he added should reflect the usage of this template, which comes wired to the other SDK capabilities (e.g. logging, IMS token checks etc...) instead of simply mentioning the usage of `node-fetch`, which is indeed used by the Generic template itself, [here](https://github.com/adobe/generator-aio-app/blob/346453ddc2442b3a9986b8274604ca2917b91a3a/generators/add-action/generic/index.js#L33).

**Comment by icaraps** [comment]
BTW it would be great if you could also add it here https://github.com/AdobeDocs/project-firefly-docs/blob/main/src/pages/documentation/guides/using_sdks/index.md so we stay in sync.

**Review by meryllblanchet — APPROVED** [review]
LGTM! Thanks @duynguyen !

**Comment by duynguyen** [comment]
@meryllblanchet - thanks for the good suggestions as always 👍

**Comment by duynguyen** [comment]
@icaraps ok I will add there.

**Review by meryllblanchet — COMMENTED** [review]
LGTM

**Pull request merged**
