### PR TITLE
First version of the logging guide

### PR DESCRIPTION
**Pull request by meryllblanchet**

### CODE REVIEW

**Comment by sarahxxu** [comment]
I wonder if we should take out the "# Logging with Project Firefly SDK" section. that seems better fitted for content in the contribution guide.

**Comment by sarahxxu** [comment]
everything else looks good to me!

**Comment by meryllblanchet** [comment]
@sarahxxu this section should be part of both guides IMHO. It applies to both contributions to the SDK **and** custom libraries and actions that would be part of a Project Firefly application.

Let me add some wording about that to make it clearer

**Comment by sarahxxu** [comment]
in that case, i think it makes more sense under contribution guide for the sdk and we link to this block from this guide (we don't want to keep duplicate texts if possible). then from the developer's perspective -- it's more like "understand how logs work behind the scenes and here's how you can enhance it by contributing", right?

**Comment by meryllblanchet** [comment]
@sarahxxu please see my update. For an end-user it is both: see how you can use `Logger` and `Errors` in your custom code, and see how you can use the CLI to retrieve these logs.

**Pull request merged**
