### PR TITLE
Update app-hooks for legacy app and app with extensions

### PR DESCRIPTION
**Pull request by shazron**
The text has been updated but the workflow diagrams have not (just have to edit out the npm script text). The text is available for review first.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by shazron** [comment]
@meryllblanchet Two new changes:
1. New workflow diagrams (changed npm script to hook) https://github.com/AdobeDocs/project-firefly/pull/132/commits/8d38de86cc40620b8639572686848f72ee20af3f
2. add note about legacy app hooks running before extension hooks https://github.com/AdobeDocs/project-firefly/pull/132/commits/82f517b5b5cd62ee3015e9c5e42078549d178edd

**Comment by meryllblanchet** [comment]
@shazron the diagrams LGTM.
I added two comments to the legacy app hooks note, please have a look.

**Comment by shazron** [comment]
edited based on comments: https://github.com/AdobeDocs/project-firefly/pull/132/commits/8374fbd4713021b3c5496492b230805566d39880

**Comment by meryllblanchet** [comment]
LGTM, thanks for your contribution to the docs @shazron !

**Pull request merged**
