### PR TITLE
Node version must be >=12.22

### PR DESCRIPTION
**Pull request by purplecabbage**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by purplecabbage** [comment]
@sarahxxu 🍾

**Comment by meryllblanchet** [comment]
@purplecabbage shouldn't that be reflected here: https://github.com/adobe/aio-cli/blob/887574e868f69cf9859cf3e6068e472f91a82bf6/package.json#L57

**Comment by fmeschbe** [comment]
Also, I would love to know the technical reason to change lower bound dependency from 10 to 12.22. Thanks.

**Comment by purplecabbage** [comment]
The latest version of parcel requires 12.x, so the app plugin must be 12.x and because the cli depends on all of its core plugins … the cli must also be 12.x

Yes, we need to update the cli check also.

**Review by meryllblanchet — APPROVED** [review]
LGTM

**Pull request merged**
