### PR TITLE
Update resources.md

### PR DESCRIPTION
**Pull request by icaraps**
* added awesome apps
* new codelabs

### CODE REVIEW

**Comment by icaraps** [comment]
cc @sarahxxu for review

**Comment by sarahxxu** [comment]
thanks a lot for adding the resources. I'm not crazy about the wording "Awesome Apps" bc there's no equivalence in the industry imho -- how about "Sample Apps" instead? cc @icaraps

**Comment by icaraps** [comment]
I'm fine with that as well. Awesome Apps is inspired from https://github.com/markusthoemmes/awesome-openwhisk :)

**Comment by schaulinsan** [comment]
+1 to keep it "awesome apps" , this is open source related

*
Florian Schaulin, AIOE Developer Enablement, fschauli@adobe.com, C +41 79 6580560

________________________________

**Comment by sarahxxu** [comment]
I lean towards "Sample App" bc that's more industry-standard to me and prob more meaningful and more searchable to readers. people are more likely to search for "sample app" than "awesome apps" (the later is mostly mobile app recommendations btw. 

for reference, that's what microsoft, google and ibm call them too.
- https://developer.android.com/samples
- https://cloud.ibm.com/docs/services/assistant?topic=assistant-sample-apps
- https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/open-and-run-a-sample-app

**Comment by schaulinsan** [comment]
quite some good arguments indeed 🙂🙂

*
Florian Schaulin, AIOE Developer Enablement, fschauli@adobe.com, C +41 79 6580560

________________________________

**Comment by sarahxxu** [comment]
updated and merging ;)

**Comment by icaraps** [comment]
Awesome 👍

**Pull request merged**
